env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - unused-imports
  - '@typescript-eslint'
ignorePatterns:
  - node_modules/**
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-nested-ternary:
    - error
  no-unused-vars:
    - error
    - local
  unused-imports/no-unused-imports:
    - error
  react/react-in-jsx-scope:
    - off

  
